In [47]:
import torch
input_ids = torch.randn((512,10))
# print(input_ids)
position_ids = torch.arange(10, dtype=torch.long, )
print(position_ids.unsqueeze(1).unsqueeze(1).unsqueeze(2))
position_ids = position_ids.unsqueeze(0).expand_as(input_ids)
print(position_ids)

tensor([[[[0]]],


        [[[1]]],


        [[[2]]],


        [[[3]]],


        [[[4]]],


        [[[5]]],


        [[[6]]],


        [[[7]]],


        [[[8]]],


        [[[9]]]])
tensor([[0, 1, 2,  ..., 7, 8, 9],
        [0, 1, 2,  ..., 7, 8, 9],
        [0, 1, 2,  ..., 7, 8, 9],
        ...,
        [0, 1, 2,  ..., 7, 8, 9],
        [0, 1, 2,  ..., 7, 8, 9],
        [0, 1, 2,  ..., 7, 8, 9]])


In [48]:
(0)*float('-inf')

nan

In [1]:
import math
import torch
q = torch.randn((1,23,512,64))
k= torch.randn((1,23,256,64))
v= torch.randn((1,23,256,64))
att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
print(att)
# print(input_ids)

tensor([[[[-1.3714, -0.2057,  1.1137,  ..., -0.2960, -0.6635, -0.7693],
          [-0.6280,  0.3645, -0.4159,  ...,  0.6154, -0.4032, -0.8866],
          [-0.6996,  0.7248, -1.2514,  ...,  2.3442,  1.0420, -0.6090],
          ...,
          [-0.6644,  1.1190,  1.3489,  ...,  0.0123, -0.3003, -0.5672],
          [ 0.4801,  0.7064,  0.4212,  ..., -0.8316, -0.1371,  0.3382],
          [-2.2111, -0.1904, -0.1388,  ..., -0.4074, -0.1828,  0.0190]],

         [[ 0.5330,  0.6032,  1.8969,  ...,  1.2574,  0.9074,  0.1238],
          [-2.9302, -0.2673, -1.7785,  ..., -1.5860, -1.2317, -0.7007],
          [-0.1392,  0.0312, -1.3816,  ..., -0.0101, -0.0267, -0.8497],
          ...,
          [-1.3216,  1.6864,  0.9327,  ..., -1.0344,  0.9940,  1.3416],
          [ 2.0405, -0.4577,  0.1687,  ...,  0.7606,  1.2857, -0.9347],
          [-1.6194, -0.7169, -1.7255,  ..., -0.8315, -2.6587,  0.2821]],

         [[ 2.4463,  0.5014,  0.4900,  ...,  0.4086,  0.1722,  1.3122],
          [ 0.6895,  1.2931,  

In [4]:
def a():
    return 1,2
a =a()
print (a)
x,y =a
print(x)
print(y)

(1, 2)
1
2
